### ISSUE TITLE
Write initial configuration instructions

### ISSUE THREAD

**Issue by jimmyandrade** [multei/api#53]
- [x] Create a `.env.example` file;
- [x] Different ports for `npm start`, `npm run debug` and `npm run develop:heroku`;
- [x] Config instructions for local environment variables on `README.md`;
- [x] Config instructions for local database on `README.md`;

**Comment by jimmyandrade** [comment]
@all-contributors please add @jimmyandrade for code

**Comment by tuliooassis** [comment]
@all-contributors please add @tuliooassis for doc

**Comment by jimmyandrade** [comment]
@all-contributors please add @jimmyandrade as code

**Comment by jimmyandrade** [comment]
@all-contributors please add @jimmyandrade for doc

**Comment by jimmyandrade** [comment]
@all-contributors add @jimmyandrade for example
